### ISSUE TITLE
Bluebird dependency not listed in published package.json

### ISSUE THREAD

**Issue by coagmano** [ClickSend/clicksend-nodejs#1]
The version published on npm does not list `bluebird` as a dependency when the package does use it here:
https://github.com/ClickSend/clicksend-nodejs/blob/e167b1f21b0c7312e002330cdcf0f865b0150673/api.ts#L15

At first glance the usage looks to be compatible with native promises. So ideally, you could just replace the line with a test for Promises, and ask consumers to polyfill promise if it doesn't exist

**Comment by picturelink** [comment]
I know this is 18 months later, but just in case people encounter this. I've [published a fork](https://www.npmjs.com/package/@picturelink/clicksend) of this which simplifies installation:

* Removes [bluebird](https://github.com/petkaantonov/bluebird) dependency as it isn't necessary for compiling.
* Distributes a compiled version of the package so compilation after installation is no longer necessary.
* Installs dependencies when installing (see [Issue #1](https://github.com/ClickSend/clicksend-nodejs/issues/1)).

**Comment by dodedodo** [comment]
Ideally I would like to see ClickSend fix its own SDK, rather than ignoring the issue and forcing community members to fork. Please re-open this issue. It's not fixed.
